allow_ffn_pad: true
alpha: 0.6
attention_dropout: 0.1
batch_size: 32
beam_size: 4
beam_width: 3
dataset_file: ../data/moli/dataset/dataset.tfrecord
decode_mode: beam_search
default_batch_size: 1024
default_batch_size_tpu: 1024
embedding_size: 128
extra_decode_length: 50
extra_reserved_tokens: [<BotName>]
filter_size: 256
hidden_size: 32
init_train: true
initializer_gain: 1.0
is_tgt_label: false
keep_prob: 0.7
label_smoothing: 0.1
layer_postprocess_dropout: 0.1
learning_rate: 2.0
learning_rate_decay_rate: 1.0
learning_rate_warmup_steps: 16000
max_length: 256
min_count: 4
model_dir: model/transformer
n_observations: 10000
num_epochs: 10
num_heads: 4
num_hidden_layers: 6
optimizer_adam_beta1: 0.9
optimizer_adam_beta2: 0.997
optimizer_adam_epsilon: 1e-09
project_name: moli
raw_data_dir: ../data/moli/raw
relu_dropout: 0.1
save_file: ../release/moli/model/transformer/model.ckpt
src_file: ../data/moli/semi/src.txt
static_batch: false
tgt_file: ../data/moli/semi/tgt.txt
update_dataset: false
update_semi: false
update_vocab: false
use_tpu: false
vocab_file: ../release/moli/vocab/vocab.txt
vocab_size: 33708
