

# model
# train or infer
mode: infer
init_train: false
droupout: 0.7
hidden_size: 128
embedding_size: 128
learning_rate: 0.002
batch_size: 32
num_epochs: 10

#decode
decode_mode: greedy
beam_width: 3
