

# model
# train or infer
mode: infer
init_train: false
droupout: 0.7
batch_size: 32
hidden_size: 128
embedding_size: 128
learning_rate: 0.002
num_epochs: 10

# label
labels:
 - weather
 - meal
 - sleep
 - sing
