

# model
# train or infer
mode: train
init_train: True
dropout_keep_prob: 0.7
batch_size: 32
hidden_size: 128
embedding_size: 64
learning_rate: 0.002
num_epochs: 3

# label
labels:
 - cancel
 - fav
 - resume
 - unfav
 - change
 - help
 - open
 - return
 - 'yes'
 - close
 - next
 - pause
 - showfav
 - exit
 - 'no'
 - previous
 - stop
